name: Pre-Tag CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Create uv virtualenv
      run: uv venv

    - name: Build wheel
      run: |
        source .venv/bin/activate
        uv build

    - name: Install test dependencies
      run: |
        source .venv/bin/activate
        uv pip install --group test
        uv pip install dist/*.whl

    - name: Run tests
      run: |
        source .venv/bin/activate
        .venv/bin/pytest

    - name: Build package
      run: uv build
