name: Pre-Tag CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CITATION.cff'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CITATION.cff'
      - 'LICENSE'
  workflow_dispatch:  # Allow manual triggers

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Create uv virtualenv
      run: uv venv

    - name: Build wheel
      run: |
        source .venv/bin/activate
        uv build

    - name: Install test dependencies
      run: |
        source .venv/bin/activate
        uv pip install --group test
        uv pip install dist/*.whl

    - name: Run tests
      run: |
        source .venv/bin/activate
        .venv/bin/pytest --pyargs vg
