name: Test Build (No Publish)

on:
  workflow_dispatch:  # Manual trigger only
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install build dependencies
      run: |
        uv pip install --system cython numpy setuptools build

    - name: Build package
      run: uv build

    - name: List built artifacts
      run: ls -lh dist/

    - name: Install package with test dependencies
      run: |
        uv pip install --system pytest
        uv pip install --system dist/*.whl

    - name: Run tests
      run: pytest --pyargs vg -v

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        path: dist/
